// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP3G4b6XnH9DjRkZu46O6kWwif5mPekFI',
    appId: '1:83307506429:web:0fc6179b2b1df1287d6c94',
    messagingSenderId: '83307506429',
    projectId: 'employee-connect-43be6',
    authDomain: 'employee-connect-43be6.firebaseapp.com',
    storageBucket: 'employee-connect-43be6.firebasestorage.app',
    measurementId: 'G-2Y14N3HFM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ZeyQUwMUFjgZspMumBhPH7aGr6-l1c4',
    appId: '1:83307506429:android:5512cf68594a6fc77d6c94',
    messagingSenderId: '83307506429',
    projectId: 'employee-connect-43be6',
    storageBucket: 'employee-connect-43be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfy77FdRtoQUMP302xy_74ANr8mNoeEEM',
    appId: '1:83307506429:ios:f7f006b5ecf9cb047d6c94',
    messagingSenderId: '83307506429',
    projectId: 'employee-connect-43be6',
    storageBucket: 'employee-connect-43be6.firebasestorage.app',
    iosBundleId: 'com.mobile.employeeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfy77FdRtoQUMP302xy_74ANr8mNoeEEM',
    appId: '1:83307506429:ios:a84dd04f09b3124f7d6c94',
    messagingSenderId: '83307506429',
    projectId: 'employee-connect-43be6',
    storageBucket: 'employee-connect-43be6.firebasestorage.app',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP3G4b6XnH9DjRkZu46O6kWwif5mPekFI',
    appId: '1:83307506429:web:6ada0094023b1ff17d6c94',
    messagingSenderId: '83307506429',
    projectId: 'employee-connect-43be6',
    authDomain: 'employee-connect-43be6.firebaseapp.com',
    storageBucket: 'employee-connect-43be6.firebasestorage.app',
    measurementId: 'G-FEXB8SL447',
  );
}
